//
//  ViewController.swift
//  BackroomSessions_TeamB
//
//  Created by Isumy Aguila on 12/2/19.
//  Copyright © 2019 Isumy Aguila. All rights reserved.
//

import UIKit

class ViewController: UIViewController {

    //I DISABLED THIS VIEW CONTROLLER THAT WAY THIS IS NOT THE INITIAL VIEW.
    //BECAUSE I SET UP THE CONTAINERCONTROLLER AS THE ROOT VIEW CONTROLLER IN THE APPDELEGATE FILE.
    //THE REST OF THE VIEW CONTROLLERS SHOULD BE EMBEDED PROGRAMATICALLY TO THE CONTAINER VIEW CONTROLL

//WE SHOULD AVOID USING THE STORYBOARD AND WE SHOULD DO EVERYTHING PROGRAMATICALLY
    
    //Regards, Isumy
}

